name: Build ZMK Firmware

on:
  push:
    paths:
      - "Firmware/ZMK/itzal_v1/**"
      - ".github/workflows/build.yml"
  pull_request:
    paths:
      - "Firmware/ZMK/itzal_v1/**"
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      config_path: Firmware/ZMK/itzal_v1
