name: Build ZMK Firmware

on:
  push:
    paths:
      - "boards/**"
      - "config/**"
      - "build.yaml"
      - "zephyr/**"
      - ".github/workflows/build.yml"
  pull_request:
    paths:
      - "boards/**"
      - "config/**"
      - "build.yaml"
      - "zephyr/**"
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
